# Generated by Django 5.1.1 on 2024-10-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0004_signup_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
