# Generated by Django 5.1.1 on 2024-10-14 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0005_hiringdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_dates',
        ),
        migrations.CreateModel(
            name='InterviewDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('hiring_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_details', to='hrmsapp.hiringdetails')),
            ],
        ),
    ]
