# Generated by Django 5.1.1 on 2024-10-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0006_remove_hiringdetails_interview_dates_interviewdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_details',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='InterviewDetail',
        ),
    ]
