# Generated by Django 5.1.1 on 2024-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0007_hiringdetails_interview_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringdetails',
            old_name='interview_details',
            new_name='interview_data',
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_location',
            field=models.JSONField(default=list),
        ),
    ]
