# Generated by Django 5.1.1 on 2024-10-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0008_rename_interview_details_hiringdetails_interview_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_data',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_location',
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_date3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_location1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_location2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_location3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
