# Generated by Django 5.1.2 on 2024-10-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0009_hrdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_social_media_Linkedin', models.JSONField(blank=True, default=list)),
                ('company_social_media_Instagram', models.JSONField(blank=True, default=list)),
                ('company_social_media_Facebook', models.JSONField(blank=True, default=list)),
                ('company_social_media_Twitter', models.JSONField(blank=True, default=list)),
                ('company_social_media_Whatsapp_group', models.JSONField(blank=True, default=list)),
                ('company_department', models.CharField(blank=True, max_length=255, null=True)),
                ('company_employees', models.IntegerField()),
                ('company_weblink', models.URLField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_branch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('company_certification', models.CharField(blank=True, max_length=100, null=True)),
                ('company_license', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HiringDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_roles', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('area_of_interest', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('passed_out', models.PositiveIntegerField()),
                ('age_no_ratio', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=20)),
                ('no_of_vacancies', models.PositiveIntegerField()),
                ('salary_details', models.CharField(max_length=100)),
                ('no_of_vacancy_required', models.PositiveIntegerField()),
                ('interview_dates', models.TextField(blank=True, null=True)),
                ('interview_locations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
