# Generated by Django 5.1.1 on 2024-10-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0009_remove_hiringdetails_interview_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_date1',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_date2',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_date3',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_location1',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_location2',
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_location3',
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_location',
            field=models.JSONField(default=list),
        ),
    ]
