# Generated by Django 5.1.1 on 2024-10-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0010_remove_hiringdetails_interview_date1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interview_location',
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interviews',
            field=models.ManyToManyField(to='hrmsapp.interview'),
        ),
    ]
