# Generated by Django 5.1.1 on 2024-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0011_interview_remove_hiringdetails_interview_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='interviews',
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_dates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hiringdetails',
            name='interview_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='age_no_ratio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='job_roles',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Manager', 'Manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='no_of_vacancies',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='no_of_vacancy_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='passed_out',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
