# Generated by Django 5.1.1 on 2024-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0012_remove_hiringdetails_interviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringdetails',
            name='job_roles',
            field=models.CharField(max_length=100),
        ),
    ]
