# Generated by Django 5.1.2 on 2024-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0017_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
