# Generated by Django 5.1.2 on 2024-11-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0013_alter_hiringdetails_job_roles'),
        ('hrmsapp', '0018_otpmodel_is_used'),
    ]

    operations = [
    ]
