# Generated by Django 5.1.2 on 2024-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0021_hiringdetails_user_hrdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_social_media',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
