# Generated by Django 5.1.2 on 2024-11-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0021_passwordresetrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
