# Generated by Django 5.1.2 on 2024-11-29 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0022_alter_hrdetails_hr_social_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hrdetails',
            name='hr_social_media',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='hrdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
