# Generated by Django 5.1.2 on 2024-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0023_alter_hrdetails_hr_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
