# Generated by Django 5.1.2 on 2024-11-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0023_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(max_length=4),
        ),
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
