# Generated by Django 5.1.2 on 2024-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0024_remove_passwordresetotp_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(default='default@domain.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
