# Generated by Django 5.1.2 on 2024-11-13 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0025_alter_passwordresetotp_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
