# Generated by Django 5.1.2 on 2024-11-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0020_companydetails_user'),
        ('hrmsapp', '0026_delete_passwordresetotp_companydetails_user_and_more'),
    ]

    operations = [
    ]
