# Generated by Django 5.1.2 on 2024-11-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0028_hiringdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='user',
        ),
    ]
