# Generated by Django 5.1.2 on 2024-12-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0024_alter_aboutme_photo'),
        ('hrmsapp', '0030_hiringdetails_certifications_hiringdetails_user'),
    ]

    operations = [
    ]
