# Generated by Django 5.1.2 on 2024-12-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmsapp', '0031_merge_20241212_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringdetails',
            name='certifications',
        ),
    ]
